version: '3.8'

services:
  test_postgres:
    image: postgres:16
    container_name: django_test_postgres
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5434:5432"  # port 5434 on host → port 5432 in container
    volumes:
      - test_pgdata:/var/lib/postgresql/data

volumes:
  test_pgdata:
