version: '3.8'

services:
  # Main development database
  postgres:
    image: postgres:16
    container_name: auth_postgres
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Test database
  test_postgres:
    image: postgres:16
    container_name: django_test_postgres
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5434:5432"
    volumes:
      - test_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis cache
  redis:
    image: redis:7.4-alpine
    container_name: auth_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
  test_pgdata: