# Generated by Django 5.2.4 on 2025-08-02 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_device',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_ip',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_login_location',
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('email_change', 'Email Change'), ('profile_update', 'Profile Update'), ('2fa_enable', '2FA Enable'), ('2fa_disable', '2FA Disable'), ('account_block', 'Account Block'), ('account_unblock', 'Account Unblock'), ('otp_request', 'OTP Request'), ('otp_verify', 'OTP Verify')], max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_device', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
